"""The corpus source list: a fixed answer, read from the corpus definition.

This is the one question the assistant answers about ITSELF rather than from a
page: "name the hdfc fund pages that you are using". It arrived as an
out-of-scope refusal, and the reason it was refused is the point of this module.

The question was classified `factual`, retrieved, and the gate closed at
`raw_dense_max=0.7540` against the calibrated threshold of 0.7562. Two
thousandths of a cosine decided it, from a question about which pages the
corpus contains. The chunks that scored highest were HDFC Equity's "Fund house"
boilerplate - the website address, the AMC's online centre - which says nothing
about what the assistant covers. So no threshold could have produced the right
answer, and neither could a prompt: the corpus pages do not describe the corpus.

Therefore the answer is the corpus definition itself. `config/corpus.yaml` is the
same file Phase 2 fetched the five pages from, it is validated at load time, and
it carries a page id, a scheme and an http(s) source URL per page. Reading it
gives five names that are true by construction.

What this deliberately does NOT do, and why:

- **No model call.** A model asked to "list the funds you cover" writes from its
  weights: it will drop a scheme, add one it knows about, or phrase the list as
  though the corpus were larger. The same refusal rationale as `educational.py` -
  a fixed policy answer is generated by nobody.
- **No retrieval, and no gate.** There is nothing to be similar to. A score is
  not evidence about the corpus's own extent, and letting one decide here is how
  the question got refused in the first place.
- **No invented URLs, and no URLs in the text at all.** The one-citation rule
  (FR-17) allows exactly one link per answer; five is not one. The verified URLs
  are recorded in the internal `validation` notes instead, where the eval harness
  and the CLI can audit them and a reader cannot be sent to a wrong page. Every
  note URL is copied from `corpus.yaml` - none is generated.
- **No weakening of the refusal paths.** This module answers ONE question shape,
  reached only through `Intent.CORPUS_SOURCES`, and that intent is decided after
  the opinion and scope rules have already had their say. "Should I buy HDFC
  Equity?" and "Do you cover the HDFC Mid Cap Fund?" are untouched, and
  `test_corpus_sources.py` asserts exactly that.
"""

from __future__ import annotations

import logging
import re

from ..core.config import Settings, load_corpus
from ..core.errors import CorpusConfigError
from ..core.models import Answer, Intent

log = logging.getLogger(__name__)

#: Sentence one lists the pages; sentence two says what that list means. Two
#: sentences, so the `Answer` contract's limit of 3 holds without trimming.
#:
#: Written to be advice-screen and performance-screen clean, exactly like the
#: refusal texts in `educational.py`: the answer names schemes, so it contains
#: "Growth" and "Tax Saver" plan vocabulary, and a future edit that says "the
#: best one is..." would turn a factual answer into a recommendation.
_LEAD = "I answer from a fixed set of {count} HDFC Direct Growth fund pages: {names}."
_TAIL = "Every fact I give comes only from those pages, and nothing outside them."

#: The plan/variant suffix, e.g. the "- Direct Plan - Growth" in
#: "HDFC ELSS Tax Saver Fund - Direct Plan - Growth". The corpus fixes one plan
#: for all five schemes (`plan_variant: Direct Growth`), so the suffix is
#: constant and the scheme name is what precedes it. Derived, never hardcoded:
#: the five names in the answer are read from corpus.yaml, and a copy of them
#: in this file would drift the moment a scheme was renamed.
_PLAN_SUFFIX = re.compile(r"\s+[-\u2013\u2014]\s+")


def display_scheme(scheme: str) -> str:
    """`HDFC ELSS Tax Saver Fund - Direct Plan - Growth` -> `HDFC ELSS Tax Saver Fund`."""
    return _PLAN_SUFFIX.split(scheme.strip(), maxsplit=1)[0].strip()


def _join(names: list[str]) -> str:
    """Oxford-joined list, so the text reads as a sentence rather than a CSV."""
    if len(names) == 1:
        return names[0]
    return f"{', '.join(names[:-1])} and {names[-1]}"


def answer_source_list(
    *,
    settings: Settings | None = None,
    checks: list[str] | None = None,
    cause: str = "question about which pages this assistant covers",
) -> Answer:
    """Answer "which pages do you cover?" from the corpus definition.

    Fails CLOSED. If `config/corpus.yaml` cannot be loaded there is no honest
    answer to give, and this returns Refusal B - the same fixed out-of-corpus
    wording as any other refusal - rather than a half-list or a remembered one.
    A missing corpus config is a broken deployment, and the honest user-facing
    output for a broken deployment is the boundary statement.
    """
    from .educational import refuse_not_in_corpus

    s = settings or Settings()
    notes = list(checks or [])

    try:
        pages = load_corpus(s)["pages"]
    except CorpusConfigError as exc:
        log.error("corpus source list unavailable: %s", exc)
        return refuse_not_in_corpus(
            intent=Intent.CORPUS_SOURCES,
            checks=notes,
            settings=s,
            cause=f"corpus definition could not be read ({exc})",
        )

    names = [display_scheme(str(page["scheme"])) for page in pages]
    notes.append(f"corpus_sources: {cause}")
    notes.append(
        f"corpus_sources: {len(names)} page(s) read from {s.corpus_file}; "
        "no retrieval, no model call, no similarity score involved"
    )
    for page in pages:
        # Internal audit trail only - the notes are never rendered. The URL is
        # copied from corpus.yaml, so this line is evidence that the citation
        # came from the corpus definition rather than from anyone's memory.
        notes.append(
            f"corpus_sources: {page['page_id']} -> {page['source_url']}"
        )

    return Answer(
        intent=Intent.CORPUS_SOURCES,
        text=f"{_LEAD.format(count=len(names), names=_join(names))} {_TAIL}",
        # No single source: this answer is about all five pages at once, and
        # naming one would imply the other four are unsupported (FR-17).
        source_url=None,
        source_title=None,
        last_updated=None,
        refused=False,
        retrieved_chunk_ids=[],
        validation=notes + [
            "advice_screen: clear (names schemes, recommends none)",
            "performance_screen: clear (no figure of any kind is stated)",
        ],
    )


__all__ = ["answer_source_list", "display_scheme"]
