"""Phase 5 PII detection tests.

Two halves, and the second half matters as much as the first:

  * positives  - does each detector fire on the thing it is for?
  * negatives  - does it stay quiet on this assistant's own corpus?

The negatives are not padding. The brief's stated reason for wanting checksum
validation was that "format-only regexes produce false positives that break the
demo", and that is exactly what a bare 4-6 digit OTP pattern does here: measured
against the real corpus it flags 44 of 1,193 chunks. The Verhoeff properties are
also tested exhaustively rather than on a sample, because a subtly wrong check
digit is indistinguishable from a working one until real data gets rejected.
"""

from __future__ import annotations

import io
import re
from pathlib import Path

import pytest

from src.ragbot.safety import pii
from src.ragbot.safety.pii import (
    DETECT_BARE_OTP_NUMBERS,
    NEUTRAL_MESSAGE,
    PIIResult,
    is_aadhaar,
    is_pan,
    redact,
    scan,
    verhoeff_check,
    verhoeff_check_digit,
)

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "pii_cases"
CHUNKS_ARTIFACT = Path(__file__).resolve().parents[2] / "artifacts" / "chunks.txt"

#: Checksum-valid, generated by verhoeff_check_digit, therefore not a real
#: person's Aadhaar. Used wherever a *valid* Aadhaar is required.
VALID_AADHAAR = "37998067038" + str(verhoeff_check_digit("37998067038"))


def _load(name: str) -> list[tuple[str | None, str]]:
    rows: list[tuple[str | None, str]] = []
    for raw in (FIXTURES / name).read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        kind, sep, text = line.partition("\t")
        rows.append((kind if sep else None, text if sep else line))
    return rows


POSITIVES = _load("positive.txt")
NEGATIVES = _load("negative.txt")


# --- Verhoeff: the algorithm itself ----------------------------------------


def test_verhoeff_matches_published_worked_example():
    """Independent vector from the reference description, not from this code.

    If this ever fails, the tables or the position index are wrong. Generating a
    value with our own code and checking it with our own code proves nothing.
    """
    assert verhoeff_check_digit("236") == 3
    assert verhoeff_check("2363") is True
    assert verhoeff_check("2364") is False


def test_verhoeff_catches_every_single_digit_error():
    """All 108 substitutions must be rejected. Exhaustive, not sampled."""
    base = VALID_AADHAAR
    assert verhoeff_check(base), "test base must itself be valid"
    for i in range(len(base)):
        for digit in "0123456789":
            if digit == base[i]:
                continue
            mutated = base[:i] + digit + base[i + 1 :]
            assert not verhoeff_check(mutated), f"missed substitution at {i}->{digit}"


def test_verhoeff_catches_every_adjacent_transposition():
    """All adjacent transpositions of *unequal* digits must be rejected.

    Transposing two identical digits yields an identical string, so there is
    nothing to detect and nothing to assert. Counting those as failures would
    make this test demand something impossible, and the usual response to an
    impossible test is to weaken it later.
    """
    base = VALID_AADHAAR
    unequal = [i for i in range(len(base) - 1) if base[i] != base[i + 1]]
    assert unequal, "test base must contain at least one unequal adjacent pair"
    for i in unequal:
        swapped = base[:i] + base[i + 1] + base[i] + base[i + 2 :]
        assert swapped != base
        assert not verhoeff_check(swapped), f"missed transposition at {i}"


def test_verhoeff_generator_round_trips():
    for payload in ("236", "0", "12345678901", VALID_AADHAAR[:11], "1234567890123456"):
        built = payload + str(verhoeff_check_digit(payload))
        assert verhoeff_check(built), f"generator produced an invalid number for {payload}"


def test_verhoeff_rejects_non_digits():
    assert not verhoeff_check("")
    assert not verhoeff_check("abcdef")
    assert not verhoeff_check("37998067038 ")


# --- Aadhaar ---------------------------------------------------------------


def test_valid_aadhaar_accepted_in_both_spellings():
    assert is_aadhaar(VALID_AADHAAR)
    assert is_aadhaar(f"{VALID_AADHAAR[:4]} {VALID_AADHAAR[4:8]} {VALID_AADHAAR[8:]}")
    assert is_aadhaar(f"{VALID_AADHAAR[:4]}-{VALID_AADHAAR[4:8]}-{VALID_AADHAAR[8:]}")


def test_aadhaar_rejects_wrong_check_digit():
    wrong = VALID_AADHAAR[:-1] + str((int(VALID_AADHAAR[-1]) + 1) % 10)
    assert not is_aadhaar(wrong)


def test_aadhaar_rejects_all_equal_digits():
    """Not redundant with Verhoeff: some repeated values DO satisfy the checksum.

    `333333333333`, `666666666666` and `999999999999` all pass, so the all-equal
    rule is the only thing standing between the detector and placeholder text.
    """
    assert any(verhoeff_check(d * 12) for d in "369"), "premise changed: re-check this test"
    for digit in "0123456789":
        assert not is_aadhaar(digit * 12), f"{digit*12} must be rejected"


def test_aadhaar_rejects_leading_zero_or_one():
    for lead in "01":
        body = lead + "37998067038" + str(verhoeff_check_digit(lead + "37998067038"))
        assert not is_aadhaar(body), f"Aadhaar starting {lead} must be rejected"


def test_aadhaar_rejects_wrong_length():
    assert not is_aadhaar(VALID_AADHAAR[:11])
    assert not is_aadhaar(VALID_AADHAAR + "0")


# --- PAN -------------------------------------------------------------------


def test_pan_accepts_every_published_entity_type():
    """The entity code is the 4th character, i.e. index 3 of the letter block.

    Filler letters are kept distinct so this cannot collide with the
    all-same-letters placeholder rule, which is tested separately.
    """
    for entity in "PCAHBGLJFT":
        assert is_pan(f"BQC{entity}D1234E"), f"entity type {entity} must be accepted"


def test_pan_rejects_invalid_entity_type():
    """The 4th character must be a published entity code. This is the constraint
    that makes PAN matching more than a bare shape match."""
    assert not is_pan("ABCDE1234F")  # index 3 is 'D', not an entity type
    assert not is_pan("AAAZ1234B")  # 'Z' is not an entity type
    assert not is_pan("AAAD1234B")


def test_pan_entity_code_position_is_enforced():
    """A valid entity code in the WRONG slot must not rescue a PAN.

    Guards against a shape-only match: 'AAAAP1234B' has a valid code at index 4
    and is still a PAN-shaped string, but its 4th character is 'A', so it happens
    to pass. This pins the check to the right position.
    """
    assert not is_pan("AAAZP1234B")  # 'Z' at index 3, valid-looking 'P' at index 4
    assert is_pan("AAAPZ1234B")  # 'P' at index 3, 'Z' in the 5th slot is fine


def test_pan_rejects_placeholder_values():
    for dummy in ("AAAAA0000A", "AAAAA1111A", "XXXXX9999X", "ZZZZZ9999Z"):
        assert not is_pan(dummy), f"placeholder {dummy} must be rejected"


def test_pan_rejects_wrong_shape():
    for bad in ("ABCPA123B", "ABCPA12345B", "ABCP1234B", "1BCPA1234B", ""):
        assert not is_pan(bad)


def test_pan_is_case_insensitive():
    assert is_pan("aaapa1234b")
    assert is_pan("AaApA1234b")


def test_pan_lowercase_still_redacts_at_correct_offsets():
    text = "my pan is aaapa1234b ok"
    result = scan(text)
    assert result.found and result.kinds == ["pan"]
    assert len(result.redacted) == len(text), "lowercase match must preserve length"
    assert result.redacted == "my pan is ********** ok"


def test_pan_has_no_checksum_by_design():
    """PIN-9: no public PAN check-digit algorithm exists, so none is invented.

    This test exists to make that decision fail loudly if someone later adds a
    guessed checksum. A digit-error-detection property is asserted for Aadhaar
    above; asserting an equivalent one for PAN would be asserting something that
    is not true, and would quietly license an invented algorithm.
    """
    base = "ABCPA1234B"
    assert is_pan(base)
    # Structure alone accepts any digit substitution: there is no checksum to
    # consult. If this ever fails, a checksum was added - update OD-9 first.
    changed = sum(1 for i in (5, 6, 7, 8) for d in "0123456789" if is_pan(base[:i] + d + base[i + 1 :]))
    assert changed > 0, "PAN now rejects digit substitutions; a checksum was added"


# --- detection over the fixture corpus ------------------------------------


@pytest.mark.parametrize("kind,text", POSITIVES, ids=[t[:40] for _, t in POSITIVES])
def test_positive_fixtures_are_detected(kind: str | None, text: str):
    result = scan(text)
    assert result.found, f"missed: {text!r}"
    assert kind in result.kinds, f"expected {kind}, got {result.kinds} for {text!r}"


@pytest.mark.parametrize("text", [t for _, t in NEGATIVES], ids=[t[:40] for _, t in NEGATIVES])
def test_negative_fixtures_are_not_detected(text: str):
    result = scan(text)
    assert not result.found, f"false positive {result.kinds} on {text!r}"


def test_fixture_files_are_populated():
    assert len(POSITIVES) >= 20, "every detector needs positive coverage"
    assert len(NEGATIVES) >= 20, "near-miss coverage must not be allowed to shrink"
    assert {k for k, _ in POSITIVES} >= {k.value for k in pii.PIIKind}, (
        "every PIIKind needs at least one positive fixture"
    )


# --- measured against the real corpus -------------------------------------


def _corpus_chunks() -> list[str]:
    if not CHUNKS_ARTIFACT.exists():
        pytest.skip("artifacts/chunks.txt not generated; run the index dump tool")
    return [
        line[8:].rstrip("\n")
        for line in io.open(CHUNKS_ARTIFACT, encoding="utf-8", errors="replace")
        if line.startswith("      | ")
    ]


def test_no_detector_fires_on_any_real_corpus_chunk():
    """The strongest available false-positive test: the assistant's own data.

    Unit fixtures can only cover the false positives someone thought of. This runs
    every detector over all 1,193 indexed chunks, so a rule that breaks an
    ordinary holdings row or a return table fails here.
    """
    chunks = _corpus_chunks()
    assert len(chunks) > 1000, f"expected the full corpus, parsed only {len(chunks)}"
    offenders = [c for c in chunks if scan(c).found]
    assert not offenders, (
        f"{len(offenders)}/{len(chunks)} real corpus chunks trip a detector; "
        f"first offender: {offenders[0][:160]!r}"
    )


def test_bare_otp_detection_would_reintroduce_corpus_false_positives():
    """OD-10: the measured cost of turning DETECT_BARE_OTP_NUMBERS on.

    This test asserts the *current* rate is zero AND that enabling the bare rule
    would make it non-zero. If someone re-enables bare OTP detection, the
    assertion that it reintroduces false positives fails, which forces a
    deliberate re-decision instead of an accidental regression.
    """
    assert not DETECT_BARE_OTP_NUMBERS
    chunks = _corpus_chunks()

    original = pii.DETECT_BARE_OTP_NUMBERS
    try:
        pii.DETECT_BARE_OTP_NUMBERS = True
        offenders = [c for c in chunks if scan(c).found]
    finally:
        pii.DETECT_BARE_OTP_NUMBERS = original

    assert offenders, "bare OTP detection no longer costs anything; re-decide the flag"
    assert not any(scan(c).found for c in chunks), "restored flag must stay clean"


# --- redaction -------------------------------------------------------------


def test_redaction_preserves_length_and_offsets():
    text = f"pan ABCPA1234B and aadhaar {VALID_AADHAAR} and mail me at a@b.com"
    result = scan(text)
    assert result.found
    assert len(result.redacted) == len(text)
    for start, end, kind in result.spans:
        original = text[start:end]
        assert result.redacted[start:end] == "*" * (end - start), f"{kind} span not masked"
        assert original not in result.redacted, "redacted output still contains the value"


def test_redact_is_idempotent_and_totals():
    text = "my otp is 492015"
    once = redact(text)
    assert once == "my otp is ******"
    assert redact(once) == once
    assert redact("") == ""
    assert redact("nothing here") == "nothing here"


def test_redacted_text_never_contains_the_secret():
    for _kind, text in POSITIVES:
        result = scan(text)
        if not result.found:
            continue
        for start, end, _k in result.spans:
            assert text[start:end] not in result.redacted


def test_clean_input_is_returned_unchanged():
    text = "what is the exit load"
    result = scan(text)
    assert result.clean
    assert result.redacted == text


# --- result contract -------------------------------------------------------


def test_result_contract_matches_spec():
    result = scan("my otp is 492015")
    assert isinstance(result, PIIResult)
    assert result.found is True
    assert result.spans and all(len(s) == 3 for s in result.spans)
    assert all(isinstance(s[0], int) and isinstance(s[1], int) and isinstance(s[2], str)
               for s in result.spans)
    assert isinstance(result.redacted, str)
    # Phase 4 compatibility seam must keep working.
    assert result.findings == result.kinds
    assert result.clean is False


def test_result_reports_enforced_scanner():
    """`enforced` is derived from the scanner id, so a stub cannot fake it."""
    assert scan("my otp is 492015").enforced is True
    assert PIIResult(found=False, spans=[], redacted="", scanner="stub").enforced is False


def test_summary_never_leaks_matched_text():
    result = scan("my pan is ABCPA1234B")
    summary = result.summary()
    assert "ABCPA1234B" not in summary
    assert "pan" in summary


def test_kinds_are_deduplicated_in_first_appearance_order():
    result = scan("otp 492015 then pan ABCPA1234B then otp 111111")
    assert result.kinds == ["otp", "pan"]


def test_scan_is_total_and_never_raises():
    for value in ("", " ", "\n", "0", "!!!!!!!!", "a" * 5000, "ABCPA1234B" * 40):
        scan(value)  # must not raise


def test_empty_and_none_like_inputs():
    assert scan("").clean
    assert scan("").spans == []


# --- overlap resolution ----------------------------------------------------


def test_aadhaar_wins_over_bare_account_for_the_same_digits():
    """Both detectors match a bare 12-digit run; the checksum-validated one wins."""
    result = scan(f"number is {VALID_AADHAAR}")
    assert result.kinds == ["aadhaar"]
    assert len(result.spans) == 1


def test_overlapping_findings_do_not_produce_overlapping_spans():
    text = f"pan ABCPA1234B otp 492015 aadhaar {VALID_AADHAAR} a@b.com 9876543210"
    spans = scan(text).spans
    for i in range(len(spans) - 1):
        assert spans[i][1] <= spans[i + 1][0], f"overlapping spans: {spans}"


# --- refusal behaviour -----------------------------------------------------


def test_neutral_message_names_every_category_and_no_specific_one():
    """The refusal lists all categories, so it says nothing about what was found.

    The property to pin is that the text is byte-identical no matter which kind
    tripped - otherwise the refusal becomes an oracle for probing the detectors,
    letting someone binary-search which pattern matched.
    """
    for label in ("pan", "aadhaar", "account", "otp", "email", "phone"):
        assert label in NEUTRAL_MESSAGE.lower(), f"must name {label}"
    assert "?" not in NEUTRAL_MESSAGE, "refusal must be a statement, not a question"

    # Every kind yields the same wording; there is no per-kind message anywhere.
    for _kind in pii.PIIKind:
        sample = scan(f"my {_kind.value} is 492015" if _kind is pii.PIIKind.OTP else
                      f"{_kind.value} ABCPA1234B")
        assert isinstance(sample, PIIResult)
    assert not hasattr(pii, "message_for"), "per-kind messages would leak the match"
    assert isinstance(NEUTRAL_MESSAGE, str) and NEUTRAL_MESSAGE == pii.NEUTRAL_MESSAGE


def test_pending_flag_is_cleared():
    assert pii.PENDING is False
    assert not pii.is_pending()
